
import type { Product } from './types';

// Omit 'id' as it will be generated by Firestore
type SeedProduct = Omit<Product, 'id'>;

export const seedData: SeedProduct[] = [
  {
    name: "fantoche triple",
    category: "alfajores",
    price: 7687.97,
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "alfajor chocolate",
    variants: [
      { id: "v_1_1", name: "chocolate", inStock: true },
      { id: "v_1_2", name: "leche", inStock: true },
      { id: "v_1_3", name: "surtido", inStock: true },
    ]
  },
  {
    name: "fantoche elixir super ddl",
    category: "alfajores",
    price: 9302.85,
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "alfajor dulce",
    variants: []
  },
  {
    name: "guaymallen simple",
    category: "alfajores",
    price: 9840.57,
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "alfajor simple",
    variants: [
      { id: "v_3_1", name: "chocolate", inStock: false },
      { id: "v_3_2", name: "leche", inStock: true },
      { id: "v_3_3", name: "surtido", inStock: false },
    ]
  },
  {
    name: "guaymallen Simple oro",
    category: "alfajores",
    price: 0,
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "alfajor oro",
    variants: []
  },
  {
    name: "Mini alfajores BON O BON",
    category: "alfajores",
    price: 2852.33,
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "alfajor bonobon",
    variants: []
  },
  {
    name: "fantoche",
    category: "alfajores",
    price: 12042,
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "alfajor fantoche",
    variants: [
      { id: "v_6_1", name: "elixir 70% cacao", inStock: true },
      { id: "v_6_2", name: "chocolate blanco", inStock: true },
    ]
  },
  {
    name: "rasta",
    category: "alfajores",
    price: 18616.47,
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "alfajor rasta",
    variants: [
      { id: "v_7_1", name: "chocolate", inStock: true },
      { id: "v_7_2", name: "blanco", inStock: true },
      { id: "v_7_3", name: "surtido", inStock: true },
    ]
  }
];

    